name: Storybook Python CI

on:
  schedule:
    - cron: "0 9 * * *"   # Every day at 9 AM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
  
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      # Step 4: Run your main script
      - name: Run Storybook Pipeline
        run: python main.py
        
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      # step 5: combine clips
      - name: combine clips
        run: ffmpeg -f concat -safe 0 -i clips_video/file_list.txt -c copy final_output.mp4
      # step6: add audio to video
      - name: Add audio to the video
        run: ffmpeg -i output_final.mp4 -i ty.wav -c:v copy -c:a aac -shortest story_book.mp4

      # Step 5: Upload results (images, audio, videos, text)
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: storybook-output
          path: story_book.mp4
